version: '3.9'

services:
  app:
    container_name: backend
    build:
      context: ./
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23111974
      POSTGRES_DB: Movie
      DATABASE_TIMEZONE: Asia/Maldives
      DATABASE_HOST: postgresdb
    ports:
      - "8080:8080"
    volumes:
      - .:/home
    depends_on:
      - postgresdb
    networks:
      - learning
    restart: always
    tty: true

  postgresdb:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23111974
      POSTGRES_DB: Movie
      TZ: Asia/Maldives
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5434:5432"
    networks:
      - learning
    restart: always

volumes:
  postgres-data:

networks:
  learning:
    driver: bridge
